### ISSUE TITLE
feat: multiple commands support

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/ruke#18]
Currently, a ruke task accepts only one command. I think that if ruke supports multiple commands per task it would be much more usable, but how?

Changing the task command ([TOML string](https://toml.io/en/v1.0.0#string)) to a vector of commands ([TOML array](https://toml.io/en/v1.0.0#array)) should work.

###### Command as string

```toml
[[tasks]]
name = "task-name"
command = "task-command"
```

###### Commands as string array

```toml
[[tasks]]
name = "task-name"
commands = [ "task-command-0", "task-command-1", "task-command-2" ]
```

Writing this manually can become boring, so here's a few changes to cover this:

- rename `add` command to `new` (alias: `n`) because it creates a **new** task
- the new `add` command should add a command to an existing task
- `remove` command should remove a specific command from the command vector
  - interactive: choice, each option is an existing command
  - non-interactive: `-i --index <INDEX>` flag
  - `-a --all` flag to remove all commands in the vector
  - if there is no command left in the vector, remove the task
